---
- name: "Download Filebeat's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
    dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
  register: download_filebeat_rpm
  until: download_filebeat_rpm is succeeded
