---
- name: "Download Filebeat's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-amd64.deb"
    dest: "/tmp/filebeat-{{ elk_stack_version }}-amd64.deb"
  register: download_filebeat_deb
  until: download_filebeat_deb is succeeded
