---
- include_tasks: "download_{{ ansible_facts.pkg_mgr }}.yml"
- include_tasks: "install_{{ ansible_facts.pkg_mgr }}.yml"

- name: enable filebeat service
  become: true
  systemd:
    name: filebeat
    enabled: yes
    masked: no
  when: ansible_virtualization_type != 'docker'

- name: Configure filebeat in SSH session
  become: true
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: start Filebeat
  when: ansible_virtualization_type != 'docker' 

- name: Configure filebeat in Docker
  become: true
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  when: ansible_virtualization_type == 'docker'

- name: Start Filebeat in Docker
  shell: "(/usr/share/filebeat/bin/filebeat --strict.perms=false --path.config /etc/filebeat --path.logs /var/log/filebeat >/dev/null 2>&1 &)"
  async: 10
  poll: 0
  changed_when: false
  when: ansible_virtualization_type == 'docker'
